modLoader="javafml"
loaderVersion="${loader_version_range}"
license="CC0-1.0"
issueTrackerURL="https://github.com/ExoHayvan/Dissolver-Enhanced/issues"

[[mods]]
modId="dissolver_enhanced"
version="${version}"
displayName="Dissolver Enhanced"
displayURL="https://github.com/ExoHayvan/Dissolver-Enhanced"
authors="ExoHayvan"
description='''Convert items into any other stored items based on its value (EMC).'''

[[dependencies.dissolver_enhanced]]
modId="forge"
mandatory=true
versionRange="${loader_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.dissolver_enhanced]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
